name: Build Windows 64-bit

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build Solution (x64 Release)
        run: msbuild SoundKeeper.sln /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v143

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: SoundKeeper-x64-Release
          path: Release/
