name: Build Windows 64-bit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build (Win64 Release)
        run: msbuild SoundKeeper.sln /p:Configuration=Release /p:Platform=Win64

      - name: Show all EXE files
        shell: pwsh
        run: Get-ChildItem -Recurse -Filter *.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SoundKeeper-Win64
          path: |
            **/*.exe
